
name: Lint Awesome List
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install awesome-lint
        run: npm install -g awesome-lint
      - name: Run awesome-lint
        run: npx awesome-lint ./README.md
